environment: 
  Testing Env:
     first URL: 'www.jj.com'
     Second URL: 'www.kkk.com'
     'DB-parameters':
        host: localhost
        port: 3306
        dbName: testdatabase
        user: root
        password: Passw@rd0123
variables:
     firstName: 'Olumide Koyenikan'
     key: 'kfjjsdkj9303hds'
   
elements:
     'login Button': '//div[@title ="dance"]'
     'Div element field': '//div'
     'username field': '//input[@id='username']'